/*
 * FreeRTOS Kernel V10.4.3
 * port.c - AVR ATmega323 / ATmega32 port
 *
 * Handles:
 *  - Stack initialisation for new tasks
 *  - Context switch (via Timer0 overflow interrupt)
 *  - Tick generation using Timer0
 *  - Critical section entry/exit
 */

#include <stdlib.h>
#include <avr/interrupt.h>
#include "FreeRTOS.h"
#include "task.h"

/*-----------------------------------------------------------
 * Implementation of functions defined in portable.h
 *----------------------------------------------------------*/

/* Start tasks with interrupts enabled */
#define portFLAGS_INT_ENABLED   ( ( StackType_t ) 0x80 )

/* Hardware constants for timer setup */
#if configUSE_16_BIT_TICKS == 1
    #define portSCALAR_TIMER_COMPARE    ( ( uint16_t ) \
        ( ( configCPU_CLOCK_HZ / configTICK_RATE_HZ ) / 8UL ) )
    #define portCLOCK_PRESCALER         ( ( uint8_t ) 2 )
    #define portCOMPARE_MATCH_A_INTERRUPT_ENABLE ( 0x10 )
#else
    #define portSCALAR_TIMER_COMPARE    ( ( uint32_t ) \
        ( ( configCPU_CLOCK_HZ / configTICK_RATE_HZ ) / 64UL ) )
    #define portCLOCK_PRESCALER         ( ( uint8_t ) 3 )
    #define portCOMPARE_MATCH_A_INTERRUPT_ENABLE ( 0x10 )
#endif

/*-----------------------------------------------------------*/

/* Initialise the stack of a task to look as if a call to
 * portSAVE_CONTEXT has already been called. */
StackType_t *pxPortInitialiseStack( StackType_t *pxTopOfStack,
                                    TaskFunction_t pxCode,
                                    void *pvParameters )
{
    uint16_t usAddress;

    /* Place a few bytes of known values on the bottom of the stack.
     * This is just useful for debugging. */
    *pxTopOfStack = 0x11;
    pxTopOfStack--;
    *pxTopOfStack = 0x22;
    pxTopOfStack--;
    *pxTopOfStack = 0x33;
    pxTopOfStack--;

    /* Simulate how the stack would look after a call to vPortYield()
     * generated by the compiler. */

    /* The start of the task code will be popped off the stack last,
     * so place it on first. */
    usAddress = ( uint16_t ) pxCode;
    *pxTopOfStack = ( StackType_t ) ( usAddress & ( uint16_t ) 0x00ff );
    pxTopOfStack--;

    usAddress >>= 8;
    *pxTopOfStack = ( StackType_t ) ( usAddress & ( uint16_t ) 0x00ff );
    pxTopOfStack--;

    /* Next simulate the stack as if after a call to portSAVE_CONTEXT().
     * portSAVE_CONTEXT places the flags on the stack immediately after r0
     * to ensure the interrupts get disabled as soon as possible, and so
     * ensuring the stack use is minimal should a context switch interrupt
     * occur. */
    *pxTopOfStack = ( StackType_t ) 0x00; /* R0 */
    pxTopOfStack--;

    *pxTopOfStack = portFLAGS_INT_ENABLED;
    pxTopOfStack--;

    /* Now the remaining registers. The compiler expects R1 to be 0. */
    *pxTopOfStack = ( StackType_t ) 0x00; /* R1 */
    pxTopOfStack--;

    /* Leave R2 - R23 untouched */
    *pxTopOfStack = ( StackType_t ) 0x02; /* R2 */
    pxTopOfStack--;
    *pxTopOfStack = ( StackType_t ) 0x03; /* R3 */
    pxTopOfStack--;
    *pxTopOfStack = ( StackType_t ) 0x04; /* R4 */
    pxTopOfStack--;
    *pxTopOfStack = ( StackType_t ) 0x05; /* R5 */
    pxTopOfStack--;
    *pxTopOfStack = ( StackType_t ) 0x06; /* R6 */
    pxTopOfStack--;
    *pxTopOfStack = ( StackType_t ) 0x07; /* R7 */
    pxTopOfStack--;
    *pxTopOfStack = ( StackType_t ) 0x08; /* R8 */
    pxTopOfStack--;
    *pxTopOfStack = ( StackType_t ) 0x09; /* R9 */
    pxTopOfStack--;
    *pxTopOfStack = ( StackType_t ) 0x10; /* R10 */
    pxTopOfStack--;
    *pxTopOfStack = ( StackType_t ) 0x11; /* R11 */
    pxTopOfStack--;
    *pxTopOfStack = ( StackType_t ) 0x12; /* R12 */
    pxTopOfStack--;
    *pxTopOfStack = ( StackType_t ) 0x13; /* R13 */
    pxTopOfStack--;
    *pxTopOfStack = ( StackType_t ) 0x14; /* R14 */
    pxTopOfStack--;
    *pxTopOfStack = ( StackType_t ) 0x15; /* R15 */
    pxTopOfStack--;
    *pxTopOfStack = ( StackType_t ) 0x16; /* R16 */
    pxTopOfStack--;
    *pxTopOfStack = ( StackType_t ) 0x17; /* R17 */
    pxTopOfStack--;
    *pxTopOfStack = ( StackType_t ) 0x18; /* R18 */
    pxTopOfStack--;
    *pxTopOfStack = ( StackType_t ) 0x19; /* R19 */
    pxTopOfStack--;
    *pxTopOfStack = ( StackType_t ) 0x20; /* R20 */
    pxTopOfStack--;
    *pxTopOfStack = ( StackType_t ) 0x21; /* R21 */
    pxTopOfStack--;
    *pxTopOfStack = ( StackType_t ) 0x22; /* R22 */
    pxTopOfStack--;
    *pxTopOfStack = ( StackType_t ) 0x23; /* R23 */
    pxTopOfStack--;

    /* Place the parameter on the stack in the correct location for
     * when the task is started. */
    usAddress = ( uint16_t ) pvParameters;
    *pxTopOfStack = ( StackType_t ) ( usAddress & ( uint16_t ) 0x00ff );
    pxTopOfStack--;

    usAddress >>= 8;
    *pxTopOfStack = ( StackType_t ) ( usAddress & ( uint16_t ) 0x00ff );
    pxTopOfStack--;

    *pxTopOfStack = ( StackType_t ) 0x26; /* R26 X */
    pxTopOfStack--;
    *pxTopOfStack = ( StackType_t ) 0x27; /* R27 X */
    pxTopOfStack--;
    *pxTopOfStack = ( StackType_t ) 0x28; /* R28 Y */
    pxTopOfStack--;
    *pxTopOfStack = ( StackType_t ) 0x29; /* R29 Y */
    pxTopOfStack--;
    *pxTopOfStack = ( StackType_t ) 0x30; /* R30 Z */
    pxTopOfStack--;
    *pxTopOfStack = ( StackType_t ) 0x31; /* R31 Z */
    pxTopOfStack--;

    return pxTopOfStack;
}

/*-----------------------------------------------------------*/

BaseType_t xPortStartScheduler( void )
{
    /* Setup Timer0 to generate the tick.
     * ATmega32 Timer0 in CTC mode, prescaler /8 */

    /* Ensure the timer is stopped */
    TCCR0 = 0x00;

    /* Set the compare value */
    OCR0 = ( uint8_t ) portSCALAR_TIMER_COMPARE;

    /* Set Timer0 to CTC mode, prescaler /8 */
    TCCR0 = ( 1 << WGM01 ) | ( 1 << CS01 );

    /* Enable Timer0 compare match interrupt */
    TIMSK |= ( 1 << OCIE0 );

    /* Restore the context of the first task that is going to run. */
    portRESTORE_CONTEXT();

    /* Simulate a function call end as generated by the compiler.
     * We will now jump to the start of the task the context of which
     * we have just restored. */
    asm volatile ( "ret" );

    /* Should not get here. */
    return pdTRUE;
}

/*-----------------------------------------------------------*/

void vPortEndScheduler( void )
{
    /* Not implemented for AVR port */
}

/*-----------------------------------------------------------*/

/* Manual context switch — called by portYIELD() */
void vPortYield( void ) __attribute__ ( ( naked ) );
void vPortYield( void )
{
    portSAVE_CONTEXT();
    vTaskSwitchContext();
    portRESTORE_CONTEXT();

    asm volatile ( "ret" );
}

/*-----------------------------------------------------------*/

/* Tick ISR — Timer0 Compare Match A
 * This fires every 1ms (configTICK_RATE_HZ = 1000)
 * It increments the tick count and may trigger a context switch */
ISR( TIMER0_COMP_vect, ISR_NAKED )
{
    portSAVE_CONTEXT();

    if( xTaskIncrementTick() != pdFALSE )
    {
        vTaskSwitchContext();
    }

    portRESTORE_CONTEXT();

    asm volatile ( "reti" );
}
